### ISSUE TITLE
VimConf

### ISSUE THREAD

**Issue by tjdevries** [leeren/dotfiles#1]
Hey Leeren,

I'm one of the core developers at github.com/neovim/neovim and was asked by the organizer of VimConf.live this year to try and reach out to you to see if you'd be interested in doing a talk. I'm not sure if you're on gitter / twitter / discord / whatever, but if you're interested in chatting, maybe we could find a way to discuss. I can give you my email or something (it's in my profile) if you're interested in doing so.

Hopefully you don't mind the weird way of reaching out :laughing: Wasn't sure how else to get a hold of you.

Thanks!

TJ

**Comment by PauloPhagula** [comment]
I think this was done. In fact, here's the talk on YouTube: https://www.youtube.com/watch?v=Gs1VDYnS-Ac

Maybe you want to close the issue? :smile

**Comment by tjdevries** [comment]
We can close, I think was for the following year, but I don't remember. Anyway, thanks :)
